$h = (Get-FileHash hello_game_ai.wasm -Algorithm SHA256).Hash.ToLower()
$parts = for ($i = 0; $i -lt 64; $i += 2) { '0x' + $h.Substring($i,2) }
$body = $parts -join ', '
$lines = @(
    '/* Auto-generated by build.bat */',
    '#ifndef HELLO_GAME_AI_HASH_H',
    '#define HELLO_GAME_AI_HASH_H',
    "static const unsigned char g_ai_hash[32] = { $body };",
    "static const char g_ai_hash_hex[] = `"$h`";",
    '#endif',
    ''
)
[System.IO.File]::WriteAllLines('ai_hash.h', $lines)
