/* Generates a 32x8 RGBA atlas: 4 tiles of 8x8 — player (white square),
 * coin (yellow ring), enemy (red blob), life icon (green heart). Deflates
 * with miniz and emits a C header. */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
/* Compiled together with miniz.c — see gen_atlas.bat. */
#include "third_party/miniz/miniz.h"
#include <stdlib.h>

#define ATLAS_W 32
#define ATLAS_H 8
#define TILE    8
#define STRIDE  (ATLAS_W * 4)

static void set_px(uint8_t* px, int x, int y, uint32_t rgba) {
    uint8_t* p = px + y * STRIDE + x * 4;
    p[0] = (uint8_t)(rgba >> 24);
    p[1] = (uint8_t)(rgba >> 16);
    p[2] = (uint8_t)(rgba >> 8);
    p[3] = (uint8_t)(rgba);
}

int main(void) {
    uint8_t raw[ATLAS_W * ATLAS_H * 4];
    memset(raw, 0, sizeof(raw));

    /* Tile 0 (x=0..7): player — solid white with a dark outline. */
    for (int y = 0; y < TILE; y++) for (int x = 0; x < TILE; x++) {
        int edge = (x == 0 || x == TILE-1 || y == 0 || y == TILE-1);
        set_px(raw, x, y, edge ? 0x222244FFu : 0xF0F0F0FFu);
    }
    /* Tile 1 (x=8..15): coin — yellow ring on transparent. */
    for (int y = 0; y < TILE; y++) for (int x = 0; x < TILE; x++) {
        int dx = x - TILE/2, dy = y - TILE/2;
        int r2 = dx*dx + dy*dy;
        uint32_t c = 0x00000000u;
        if (r2 >= 3 && r2 <= 12) c = 0xFFD000FFu;
        else if (r2 < 3)         c = 0xFFFFC080u;  /* inner glow */
        set_px(raw, 8 + x, y, c);
    }
    /* Tile 2 (x=16..23): enemy — solid red diamond. */
    for (int y = 0; y < TILE; y++) for (int x = 0; x < TILE; x++) {
        int dx = (x < TILE/2 ? x : TILE-1-x);
        int dy = (y < TILE/2 ? y : TILE-1-y);
        int inside_diamond = (dx + dy) >= 1;  /* a 6x6 diamond with 1-px border */
        uint32_t c = inside_diamond ? 0xE02030FFu : 0x00000000u;
        set_px(raw, 16 + x, y, c);
    }
    /* Tile 3 (x=24..31): life icon — green heart-ish. */
    for (int y = 0; y < TILE; y++) for (int x = 0; x < TILE; x++) {
        int fx = (x < TILE/2 ? x : TILE-1-x);
        int inside = (y <= 5) && (fx >= (y < 3 ? 1 : 0));
        set_px(raw, 24 + x, y, inside ? 0x20C040FFu : 0x00000000u);
    }

    /* Deflate with miniz (raw deflate — no wrapper). */
    unsigned long clen = compressBound((unsigned long)sizeof(raw));
    uint8_t* cbuf = (uint8_t*)malloc(clen);
    if (compress2(cbuf, &clen, raw, sizeof(raw), 9) != Z_OK) return 1;

    printf("/* Auto-generated by examples/hello_game/gen_atlas.c */\n");
    printf("#ifndef HELLO_GAME_ASSETS_H\n#define HELLO_GAME_ASSETS_H\n\n");
    printf("#define ATLAS_WIDTH  %d\n", ATLAS_W);
    printf("#define ATLAS_HEIGHT %d\n", ATLAS_H);
    printf("#define ATLAS_TILE_SIZE %d\n", TILE);
    printf("#define ATLAS_DECOMPRESSED_BYTES %d\n\n", (int)sizeof(raw));
    printf("static const unsigned char g_atlas_deflate[%d] = {\n    ", (int)clen);
    for (unsigned long i = 0; i < clen; i++) {
        printf("0x%02X,%s", cbuf[i], ((i % 16) == 15) ? "\n    " : " ");
    }
    printf("\n};\n\n#endif\n");
    free(cbuf);
    return 0;
}
